/**
 * renderFixtures.js — Fixture Renderer
 *
 * Renders every scenario in test/scenarios.js to a real values.yaml file on
 * disk so `helm template` can be run against them. This is the bridge between
 * the unit tests and the chart itself: the unit tests prove the output is what
 * we intended, `helm template` proves the chart accepts it.
 *
 * Run with:  npm run fixtures [outputDir]
 *
 * Output:    tmp/fixtures/<scenario>.yaml   (default, gitignored)
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import yaml from 'js-yaml'
import { transformAnswers } from '../src/transform.js'
import { scenarios } from '../test/scenarios.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const outputDir = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(__dirname, '../tmp/fixtures')

fs.rmSync(outputDir, { recursive: true, force: true })
fs.mkdirSync(outputDir, { recursive: true })

for (const scenario of scenarios) {
  const values = transformAnswers(scenario.answers)
  const text = yaml.dump(values, { indent: 2, lineWidth: -1 })
  const file = path.join(outputDir, `${scenario.name}.yaml`)

  fs.writeFileSync(file, `# ${scenario.description}\n# Generated by npm run fixtures - do not edit.\n${text}`)
  process.stdout.write(`[fixtures] ${scenario.name}.yaml\n`)
}

process.stdout.write(`[fixtures] ${scenarios.length} fixture(s) written to ${path.relative(process.cwd(), outputDir)}\n`)
