/**
 * renderFixtures.js — Fixture Renderer
 *
 * Renders every scenario in test/scenarios.js to a real values.yaml file on
 * disk so `helm template` can be run against them. This is the bridge between
 * the unit tests and the chart itself: the unit tests prove the output is what
 * we intended, `helm template` proves the chart accepts it.
 *
 * Run with:  npm run fixtures [outputDir]
 *
 * Output:    tmp/fixtures/<version>/<scenario>.yaml   (default, gitignored)
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { dumpValues } from '../src/yaml.js'
import { transformAnswers } from '../src/transform.js'
import { SUPPORTED_VERSIONS } from '../src/chartVersions.js'
import { scenarios } from '../test/scenarios.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const outputDir = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(__dirname, '../tmp/fixtures')

fs.rmSync(outputDir, { recursive: true, force: true })
fs.mkdirSync(outputDir, { recursive: true })

// One subdirectory per supported release. The same scenario can produce
// different values on different charts, so each has to be rendered against the
// chart it targets.
let written = 0

for (const chart of SUPPORTED_VERSIONS) {
  const versionDir = path.join(outputDir, chart.key)
  fs.mkdirSync(versionDir, { recursive: true })

  for (const scenario of scenarios) {
    const values = transformAnswers({ ...scenario.answers, chartVersion: chart.key })
    const text = dumpValues(values)
    const file = path.join(versionDir, `${scenario.name}.yaml`)

    fs.writeFileSync(
      file,
      `# ${scenario.description}\n` +
      `# Camunda ${chart.appVersion}, chart ${chart.version}.\n` +
      `# Generated by npm run fixtures - do not edit.\n${text}`,
    )
    written++
  }

  process.stdout.write(`[fixtures] ${chart.key}: ${scenarios.length} fixture(s)\n`)
}

process.stdout.write(`[fixtures] ${written} file(s) written to ${path.relative(process.cwd(), outputDir)}\n`)
